;;;;
;;;; File generated by cpct_aks2c CPCtelera script
;;;; Souce file of this conversion: src/assets/Inside_the_anthill_3.aks
;;;; Generation time: vie 03 dic 2021 13:20:41 CET
;;;;

;;;; Song 'musica' metadata constants
musica_address = 0x3500
musica_size    = 210
musica_end     = 0x35d1

;;;; Song 'musica' declaration
.globl _musica
